### ISSUE TITLE
[Request] Get name of widget

### ISSUE THREAD

**Issue by jurialmunkey** [drinfernoo/screensaver.arctic.mirage#2]
Is there a way to get the widget name? - e.g. If I select "Recently Added Movies" I'd like to retrieve that label.

**Comment by drinfernoo** [comment]
Actually, I forgot it should already be doing this! The skin string should be `screensaver.arctic.mirage.name` 😄

**Comment by jurialmunkey** [comment]
Ah I tried `screensaver.arctic.mirage.label` and `screensaver.arctic.mirage.widgetname` but didn't think to just try name!

Maybe it would be good to have an option to edit the label though. I just added a screensaver widget from TMDBHelper and the label is "TheMovieDB Helper - Trending This Week" which is pretty long. It would be good to edit it down to just "Trending Movies" or something like that.

**Comment by drinfernoo** [comment]
Should be doable 👍 I'll have to look into it in the next few days.

Where are you showing the widget title in the screensaver?

**Comment by drinfernoo** [comment]
I just pushed 1.1 to the repo, which has a setting to change the label :+1:

**Comment by jurialmunkey** [comment]
> 
> 
> Should be doable 👍 I'll have to look into it in the next few days.
> 
> Where are you showing the widget title in the screensaver?
> 
> EDIT: I just looked at AH and saw... top-left?

Yeah top left. I just disabled it for the time being because the really long label was a bit intrusive. I'll re-enable it now! Thanks 😁
