### ISSUE TITLE
[Feature Request] Keep screensaver window focused after action

### ISSUE THREAD

**Issue by jurialmunkey** [drinfernoo/screensaver.arctic.mirage#3]
Hey, so I've got an idea for this. Wondering if it is possible to have the screensaver stay active and have focus even after a user action.

I've implemented a showcase window in AH that I think might make a really great screensaver. You can see it in action in window 1141 in the current master.

So basically the idea is that when the screensaver launches you get this window:
![Honeyview_screenshot654](https://user-images.githubusercontent.com/4618719/77242347-98cddb00-6c51-11ea-9b77-4f5b3108df2e.jpg)

The background images autoscroll. Below are recommendations based on the current item. However, unlike a normal screensaver, if the user presses a direction the screensaver window stays active (rather than closing). 

Pressing down will slide these up and the user can scroll through them. They can press up to get back to the "showcase" part.

![Honeyview_screenshot655](https://user-images.githubusercontent.com/4618719/77242353-9bc8cb80-6c51-11ea-8632-ae266c80be2a.jpg)

The user would exit by pressing back. I could also add a "Close" button just in case it isn't obvious how to get out.

Do you think this is possible to achieve? I've already got the window coded up and it also launches fine if you copy it over into the mirage window xml. It's just a matter of being able to keep the focus in the screensaver.

It might even be as simple as a screensaver addon that launches `ActivateWindow(1141)` and then exits.

**Comment by jurialmunkey** [comment]
Video:
https://1drv.ms/u/s!AnrvbZV2rJqBkV26_iYkGMJFu4ky?e=27eazf

**Comment by drinfernoo** [comment]
I've also been thinking about this. @skyfsza has one working (all on the skin side, as far as I know, since he's using my base as well 😉) that you can at least scroll between the items, so I would assume it's possible.

**Comment by skyfsza** [comment]
Should be  easy to do, the screensaver is technically just doing an ActivateWindow and launching your custom window.

https://github.com/skyfsza/skin.auramod/blob/master/1080i/Custom_Screensaver_1166.xml

Inside the custom window, just set your onclicks/onright/onleft etc for  your list.

**Comment by drinfernoo** [comment]
@jurialmunkey Can you set that as a widget?

**Comment by jurialmunkey** [comment]
> 
> 
> Should be easy to do, the screensaver is technically just doing an ActivateWindow and launching your custom window.
> 
> https://github.com/skyfsza/skin.auramod/blob/master/1080i/Custom_Screensaver_1166.xml
> 
> Inside the custom window, just set your onclicks/onright/onleft etc for your list.

What is calling this custom window? Or this a feature of this addon that I don't know about? I thought it just called the scripted window `screensaver-arctic-mirage.xml`

Either way I've managed to get it working another way by closing the screensaver window onload and the launching the custom window onunload of the screensaver.

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey Can you set that as a widget?

Not yet. Eventually I will replace the fullscreen widget with it. Just want to get it all nailed down before implementing as the widget because the navigation will be a little tricky to get right.

**Comment by drinfernoo** [comment]
Sounds beautiful. I've only just gotten to sit down to play with the screensaver showcase, and I cant wait to have that on a home screen 😁
